### ISSUE TITLE
make an android app for fun but I'm stuck

### ISSUE THREAD

**Issue by Perry-chouteau** [seanwlk/wfbot#20]
Hello,

I'm trying to make an android warface tracker App for fun, but I can't find warface api.
Then I try to find someone who did it, like warfaceTracker or Warface Truesight, and I found you, can you explain me what did you do in JS, or how the api work or just a documentation, to use it..
thank you so much, for your help !

**Comment by seanwlk** [comment]
Hi, i actually wanted to release an OpenAPI version of my custom Rest APIs but never had time to release a proper documentation.
What you can do now if you want to use my APIs is to check in this repo the commands folder and get the api.wfstats.cf endpoints. They are pretty much self explainatory and i formatted them in a way so that they can be user friendly.

If you need further info just contact me on discord since this is not repo related. I'm on the official international discord. Just ask about me  there if you don't see me online.

Disclaimer:
I wanted in th future to release the APIs with bearer key to avoid abuse since it's using my server resources and it's pretty much 10x better than official ones.

**Comment by seanwlk** [comment]
I finished the documentation for my custom APIs and it's available here: https://app.swaggerhub.com/apis-docs/wfstats/WFStats/

Info about the officially available ones can be found here: https://ru.warface.com/wiki/index.php/API
